server:
  port: 8080

# API Gateway routes configuration
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**
        - id: comment-service
          uri: http://comment-service:8082
          predicates:
            - Path=/comment/**
        - id: video-service
          uri: http://video-service:8083
          predicates:
            - Path=/video/**
